import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header/Header";
import Comet from "@/components/Comet/Comet";
import Particals from "@/components/Particals/Particals";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Particals top={2} />
        <Header />
        <div className="line" />
        <div className="line line2" />
        <Comet />
        <div className="w-[1100px]">{children}</div>
      </body>
    </html>
  );
}
